### ISSUE TITLE
Unable to run the script..

### ISSUE THREAD

**Issue by Rich28** [jemrobinson/uk-tax-report#8]
Hi, Big thanks for developing this immensely useful CGT utility for PP.  I'm tying to use this on a Windows PC, but haven't worked out how to run the script, maybe (???) because I've failed to install one of its python dependencies.  

As things stand poetry, poetry-core and python-dateutil are installed and I've been attempting to run the script from the active folder which contains both the csv and PP.xml files.  The command I've thus far tried in respect of the latter has been 
`poetry run python process.py --xml All_transactions.csv --tax-year 23-24 --GIA`, though doing this generates a Traceback/module not found error detailed as follows:-

```
Creating virtualenv uk-tax-report-Oz1Rpp7G-py3.12 in C:\Users\abc\AppData\Local\pypoetry\Cache\virtualenvs
Traceback (most recent call last):
  File "C:\PPactive\process.py", line 13, in <module>
    from uk_tax_report import Account
  File "C:\PPactive\uk_tax_report\__init__.py", line 2, in <module>
    from .account import Account
  File "C:\PPactive\uk_tax_report\account.py", line 8, in <module>
    from .converters import as_currency
  File "C:\PPactive\uk_tax_report\converters.py", line 10, in <module>
    from dateutil.parser import parse
ModuleNotFoundError: No module named 'dateutil'  
```

**Comment by jemrobinson** [comment]
Hi @Rich28. You should be able to install the dependencies by running `pip install .`. Let me know if you have any problems or other questions - this has only been for my personal use so I haven't written much helpful documentation!

N.B. You probably need `--account-names "GIA"` not `--GIA`

**Comment by jemrobinson** [comment]
@Rich28 : any luck with this?

**Comment by Rich28** [comment]
Hi, thanks for getting back to me.  Truth be said I was suddenly up against it in terms of meeting the submission deadline, and just didn't have time to consider this further.  I do want to get back to it though, I'm still using PP and sadly CGT hasn't gone away...
